### ISSUE TITLE
Order of items in the class

### ISSUE THREAD

**Issue by pawelkmpt** [conversionxl/phpcs-ruleset#6]
Slevomat has [`ClassStructureSniff`](https://github.com/slevomat/coding-standard/blob/master/SlevomatCodingStandard/Sniffs/Classes/ClassStructureSniff.php) which is used for sorting class properties and methods in predefined order (eg. private properties first, etc.).

This makes sense in general, but I'm not convinced about blindly using it. The case I don't like specifically is moving `private function boot()` to the lower part of the class.

`boot()` or `init()` (depending on the class but we should strive for using `boot()`) is the place where new class object is initialized and gives you general look for what is happening in the class.

Usually code in bootable class looks like this:

```php
public function __construct() {
    $this->boot();
}
```

and in my opinion `boot()` should be placed just below `__construct()` so both starting points are next to each other. Sure, I can jump to `boot()` in Storm but... I need to jump, sometimes few hundreds lines of code. IMO this should be at the top, not hidden between strictly functional methods.

I'm not sure if this is possible to configure but I'd like to read you opinions about it @lkraav @saas786 @paulkirspuu @kylebrodeur

**Comment by saas786** [comment]
https://github.com/slevomat/coding-standard/issues/1098

**Comment by pawelkmpt** [comment]
> [slevomat/coding-standard#1098](https://github.com/slevomat/coding-standard/issues/1098)

It looks like it's not possible :(

**Comment by saas786** [comment]
Since: https://github.com/conversionxl/phpcs-ruleset/commit/1483a719d2876113692d7dacd7137dac7ec0e2fe

It should not be an issue anymore.

`SlevomatCodingStandard.Classes.ClassStructure.IncorrectGroupOrder` is excluded.

Ref: https://github.com/conversionxl/phpcs-ruleset/blob/1483a719d2876113692d7dacd7137dac7ec0e2fe/CXL/ruleset.xml#L140

But if we want to have order applied, we can temporarily include this rule by commenting it out, and so it adjusts the order, and we can reformat code for old ordered function, so they are not shown as changed in commit.

And commit.

**Comment by pawelkmpt** [comment]
Excluded is good.
